basketball:
  teams:
    - name: Gettin' Wiggy With It
      players: aaa, bbb, ccc
    - name: Sultan
      players: eee, bbbooo, ccocococ
    - name: farisha
      players: cdcd, ssadasf, asdibi
    - name: lol
      players: asdiu, ashfcvb, asiydfgb
